name: Deploy to GitHub Pages

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm ci || npm install
          fi
        continue-on-error: true
          
      - name: Build project
        run: |
          echo "Preparing deployment files..."
          # 确保docs目录存在
          mkdir -p docs
          
          # 如果有silkroadstar.html，复制为index.html
          if [ -f silkroadstar.html ]; then
            cp silkroadstar.html docs/index.html
          fi
          
          # 复制必要的资源文件
          if [ -d assets ]; then
            cp -r assets docs/ || true
          fi
          
          if [ -d js ]; then
            cp -r js docs/ || true
          fi
          
          if [ -d css ]; then
            cp -r css docs/ || true
          fi
          
          # 确保index.html存在
          if [ ! -f docs/index.html ]; then
            echo "Warning: docs/index.html not found"
          fi
        continue-on-error: true
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
